<?php

namespace CodeFlix\Repositories;

use CodeFlix\Media\ThumbUploads;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use CodeFlix\Models\Video;


/**
 * Class VideoRepositoryEloquent
 * @package namespace CodeFlix\Repositories;
 */
class VideoRepositoryEloquent extends BaseRepository implements VideoRepository
{
    use ThumbUploads;

    public function update(array $attributes, $id)
    {
        $model = parent::update($attributes, $id); // TODO: Change the autogenerated stub
        if(isset($attributes['categories'])){
            $model->categories()->sync($attributes['categories']);

        }
        return $model;
    }

    public function model()
    {
        return Video::class;
    }



    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
